version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports: 
      - target: 5672
        published: 5672
        protocol: tcp
        mode: host
      - target: 15672
        published: 15672
        protocol: tcp
        mode: host

  worker-math:
    build:
      context: ./worker-math
      dockerfile: Dockerfile.dev
    volumes: 
      - ./worker-math:/home/worker/worker-math

  worker-fib:
    build:
      context: ./worker-fib
      dockerfile: Dockerfile.dev
    volumes: 
      - ./worker-fib:/home/worker/worker-fib

  celery-test:
    build:
      context: ./test
      dockerfile: Dockerfile.dev
    volumes:
      - ./test:/home/tester/app

